/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiReviewsRouteImport } from './routes/api/reviews'
import { Route as ApiLeadsSubmitRouteImport } from './routes/api/leads.submit'
import { Route as ApiLeadsUpdateRouteImport } from './routes/api/leads.update'
import { Route as ApiReviewsModerateRouteImport } from './routes/api/reviews.moderate'
import { Route as ApiReviewsSubmitRouteImport } from './routes/api/reviews.submit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewsRoute = ApiReviewsRouteImport.update({
  id: '/api/reviews',
  path: '/api/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsSubmitRoute = ApiLeadsSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiLeadsUpdateRoute = ApiLeadsUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiLeadsRoute,
} as any)
const ApiReviewsModerateRoute = ApiReviewsModerateRouteImport.update({
  id: '/moderate',
  path: '/moderate',
  getParentRoute: () => ApiReviewsRoute,
} as any)
const ApiReviewsSubmitRoute = ApiReviewsSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiReviewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRouteWithChildren
  '/api/leads/submit': typeof ApiLeadsSubmitRoute
  '/api/leads/update': typeof ApiLeadsUpdateRoute
  '/api/reviews/moderate': typeof ApiReviewsModerateRoute
  '/api/reviews/submit': typeof ApiReviewsSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRouteWithChildren
  '/api/leads/submit': typeof ApiLeadsSubmitRoute
  '/api/leads/update': typeof ApiLeadsUpdateRoute
  '/api/reviews/moderate': typeof ApiReviewsModerateRoute
  '/api/reviews/submit': typeof ApiReviewsSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/leads': typeof ApiLeadsRouteWithChildren
  '/api/reviews': typeof ApiReviewsRouteWithChildren
  '/api/leads/submit': typeof ApiLeadsSubmitRoute
  '/api/leads/update': typeof ApiLeadsUpdateRoute
  '/api/reviews/moderate': typeof ApiReviewsModerateRoute
  '/api/reviews/submit': typeof ApiReviewsSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/leads'
    | '/api/reviews'
    | '/api/leads/submit'
    | '/api/leads/update'
    | '/api/reviews/moderate'
    | '/api/reviews/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/leads'
    | '/api/reviews'
    | '/api/leads/submit'
    | '/api/leads/update'
    | '/api/reviews/moderate'
    | '/api/reviews/submit'
  id:
    | '__root__'
    | '/'
    | '/api/leads'
    | '/api/reviews'
    | '/api/leads/submit'
    | '/api/leads/update'
    | '/api/reviews/moderate'
    | '/api/reviews/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLeadsRoute: typeof ApiLeadsRouteWithChildren
  ApiReviewsRoute: typeof ApiReviewsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reviews': {
      id: '/api/reviews'
      path: '/api/reviews'
      fullPath: '/api/reviews'
      preLoaderRoute: typeof ApiReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads/submit': {
      id: '/api/leads/submit'
      path: '/submit'
      fullPath: '/api/leads/submit'
      preLoaderRoute: typeof ApiLeadsSubmitRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/leads/update': {
      id: '/api/leads/update'
      path: '/update'
      fullPath: '/api/leads/update'
      preLoaderRoute: typeof ApiLeadsUpdateRouteImport
      parentRoute: typeof ApiLeadsRoute
    }
    '/api/reviews/moderate': {
      id: '/api/reviews/moderate'
      path: '/moderate'
      fullPath: '/api/reviews/moderate'
      preLoaderRoute: typeof ApiReviewsModerateRouteImport
      parentRoute: typeof ApiReviewsRoute
    }
    '/api/reviews/submit': {
      id: '/api/reviews/submit'
      path: '/submit'
      fullPath: '/api/reviews/submit'
      preLoaderRoute: typeof ApiReviewsSubmitRouteImport
      parentRoute: typeof ApiReviewsRoute
    }
  }
}

interface ApiLeadsRouteChildren {
  ApiLeadsSubmitRoute: typeof ApiLeadsSubmitRoute
  ApiLeadsUpdateRoute: typeof ApiLeadsUpdateRoute
}

const ApiLeadsRouteChildren: ApiLeadsRouteChildren = {
  ApiLeadsSubmitRoute: ApiLeadsSubmitRoute,
  ApiLeadsUpdateRoute: ApiLeadsUpdateRoute,
}

const ApiLeadsRouteWithChildren = ApiLeadsRoute._addFileChildren(
  ApiLeadsRouteChildren,
)

interface ApiReviewsRouteChildren {
  ApiReviewsModerateRoute: typeof ApiReviewsModerateRoute
  ApiReviewsSubmitRoute: typeof ApiReviewsSubmitRoute
}

const ApiReviewsRouteChildren: ApiReviewsRouteChildren = {
  ApiReviewsModerateRoute: ApiReviewsModerateRoute,
  ApiReviewsSubmitRoute: ApiReviewsSubmitRoute,
}

const ApiReviewsRouteWithChildren = ApiReviewsRoute._addFileChildren(
  ApiReviewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLeadsRoute: ApiLeadsRouteWithChildren,
  ApiReviewsRoute: ApiReviewsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
